import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Goals from '../features/Goals';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Goals />
      </main>

      <Footer />
    </div>
  )
}
